-- Drop all tables
DROP TABLE IF EXISTS "likes" CASCADE;
DROP TABLE IF EXISTS "comments" CASCADE;
DROP TABLE IF EXISTS "ai_sources" CASCADE;
DROP TABLE IF EXISTS "CuratedSource" CASCADE;
DROP TABLE IF EXISTS "ShoeMedia" CASCADE;
DROP TABLE IF EXISTS "reviews" CASCADE;
DROP TABLE IF EXISTS "shoes" CASCADE;
DROP TABLE IF EXISTS "verification_tokens" CASCADE;
DROP TABLE IF EXISTS "sessions" CASCADE;
DROP TABLE IF EXISTS "accounts" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

-- Drop all enums
DROP TYPE IF EXISTS "MediaStatus";
DROP TYPE IF EXISTS "ShoeMediaSource";
DROP TYPE IF EXISTS "CuratedSourceStatus";
DROP TYPE IF EXISTS "CuratedSourceType";
